server:
  port: 8081
mybatis:
  mapper-locations: classpath:mybatis/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver